[package]
edition = "2024"
name = "auth"
version = "0.1.0"

[dependencies]
axum = { version = "0.8" }
async-graphql-axum = { version = "7.0" }
dotenv = "0.15.0"
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3.17" }
anyhow = "1.0.104"
oauth2 = "5.0.0"
serde = "1"

[dependencies.sea-orm]
version = "~2.0.0-rc.40"
features = [
  "sqlx-sqlite",
  "runtime-tokio-native-tls",
  "seaography",
  "schema-sync",
  "entity-registry",
]

[dependencies.seaography]
version = "~2.0.0-rc.9"                                          # seaography version
features = ["graphql-playground", "with-decimal", "with-chrono"]

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.103" }

[workspace]
members = []

[features]
rbac = ["seaography/rbac"]
field-pluralize = ["seaography/field-pluralize"]
